# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tradu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origintitle', models.CharField(max_length=40)),
                ('origintext', models.TextField()),
                ('publicdate', models.DateField(default=True)),
                ('transtitle', models.CharField(max_length=40)),
                ('transtext', models.TextField()),
                ('transdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
