# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradu',
            name='publilink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradu',
            name='translink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradu',
            name='transupdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tradu',
            name='publicdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tradu',
            name='transdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
