# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translation', '0002_auto_20170221_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradu',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tradu',
            name='origintext',
            field=models.TextField(verbose_name='texto original'),
        ),
        migrations.AlterField(
            model_name='tradu',
            name='origintitle',
            field=models.CharField(max_length=40, verbose_name='título original'),
        ),
        migrations.AlterField(
            model_name='tradu',
            name='publicdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='fecha de la publicación'),
        ),
        migrations.AlterField(
            model_name='tradu',
            name='publilink',
            field=models.URLField(blank=True, null=True, verbose_name='link a la publicación'),
        ),
        migrations.AlterField(
            model_name='tradu',
            name='transdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='comienzo de la traducción'),
        ),
        migrations.AlterField(
            model_name='tradu',
            name='translink',
            field=models.URLField(blank=True, null=True, verbose_name='link a la traducción'),
        ),
        migrations.AlterField(
            model_name='tradu',
            name='transtext',
            field=models.TextField(verbose_name='texto traducido'),
        ),
        migrations.AlterField(
            model_name='tradu',
            name='transtitle',
            field=models.CharField(max_length=40, verbose_name='título traducido'),
        ),
        migrations.AlterField(
            model_name='tradu',
            name='transupdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='última actualización de la traducción'),
        ),
    ]
