# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 12:59
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_auto_20170222_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradu',
            name='content',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
